# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for 인수인계10분 (handover-analyzer-mvp1) - PyArmor
obfuscated build.

Same onefile/windowed build as handover_analyzer.spec, but the entry point
and all first-party app/ modules come from obf_app/ (generated by
`pyarmor gen`, see scripts/build_exe_obfuscated.ps1) instead of the plain
app/ source tree. Third-party libraries (site-packages) are never
obfuscated - only our own app/ code goes through PyArmor.

PyArmor trial license cannot obfuscate very large single files ("out of
license" - undocumented trial line/size cap observed empirically between
~552 and ~1388 lines). The 6 files over that cap
(app/ui/main_window.py, app/services/rag_package_builder.py,
app/services/rag_search.py, app/ui/chatbot_dialog.py,
app/services/report_writer.py, app/ui/memodialog.py) are copied into
obf_app/ as plain, unobfuscated source by the build script - PyInstaller
still bundles them (as regular compiled .pyc, same as the non-obfuscated
build), they're just not protected. A paid PyArmor license removes this
cap and would let all of app/ be obfuscated uniformly.
"""

from PyInstaller.utils.hooks import collect_data_files, collect_submodules

block_cipher = None

APP_NAME = "인수인계10분(난독화)"

datas = [
    ("style.qss", "."),
]
datas += collect_data_files("googleapiclient")

binaries = [
    ("obf_app/pyarmor_runtime_000000/pyarmor_runtime.pyd", "pyarmor_runtime_000000"),
]


# PyArmor obfuscation replaces every first-party module's visible source with
# an opaque `__pyarmor__(...)` call, so PyInstaller's static modulegraph
# analysis can no longer see any `import X` statements - not even between our
# own app.* submodules (e.g. app/main.py's `from app.ui.main_window import
# MainWindow` is invisible too). Two consequences, both worked around here:
#
# 1. `app` itself never gets discovered/bundled as an importable package at
#    all (only main.py, the literal entry script, is included automatically)
#    -> collect_submodules("app") walks obf_app/app/ on disk (not by parsing
#    imports) and force-includes every app.* module by name regardless of
#    obfuscation, fixing "No module named 'app'" at runtime.
# 2. Third-party packages (PySide6, docx, ...) are equally invisible, so
#    their PyInstaller hooks (which pull in Qt DLLs, data files, etc.) never
#    fire -> list every top-level third-party package app/ imports (checked
#    via grep across app/*.py) explicitly; once PyInstaller has a hiddenimport
#    entry for a *real*, non-obfuscated site-packages module, its hooks and
#    further static analysis resume normally from there.
hiddenimports = collect_submodules("app") + [
    "pyarmor_runtime_000000",
    "PySide6.QtCore",
    "PySide6.QtGui",
    "PySide6.QtWidgets",
    "docx",
    "extract_msg",
    "googleapiclient",
    "googleapiclient.discovery",
    "googleapiclient.errors",
    "googleapiclient.http",
    "numpy",
    "olefile",
    "openpyxl",
    "pdfplumber",
    "pptx",
    "xlrd",
]

a = Analysis(
    ["obf_app/app/main.py"],
    pathex=["obf_app"],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    cipher=block_cipher,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name=APP_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
